server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${doupo.datasource.driver-class-name}
      url: jdbc:mysql://${doupo.datasource.host}:${doupo.datasource.port}/${doupo.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${doupo.datasource.username}
      password: ${doupo.datasource.password}
  redis:
    host: ${doupo.redis.host}
    port: ${doupo.redis.port}
    password: ${doupo.redis.password}
    database: ${doupo.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.doupo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      doupo:
        mapper: debug
        service: info
        controller: info

doupo:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: doupo-takeout-admin-Siborne
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: doupo-takeout-user-Siborne
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${doupo.alioss.endpoint}
    access-key-id: ${doupo.alioss.access-key-id}
    access-key-secret: ${doupo.alioss.access-key-secret}
    bucket-name: ${doupo.alioss.bucket-name}
  wechat:
    appid: ${doupo.wechat.appid}
    secret:  ${doupo.wechat.secret}
    mchid: ${doupo.wechat.mchid}
    mch-serial-no: ${doupo.wechat.mch-serial-no}
    private-key-file-path: ${doupo.wechat.private-key-file-path}
    api-v3-key: ${doupo.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${doupo.wechat.we-chat-pay-cert-file-path}
    notify-url: ${doupo.wechat.notify-url}
    refund-notify-url: ${doupo.wechat.refund-notify-url}
  shop:
    address: ${doupo.shop.address}
  baidu:
    ak: ${doupo.baidu.ak}